### model
model_name_or_path: /n/holylabs/LABS/sham_lab/Users/jbejjani/DeepSeek-V3/models/DeepSeek-R1-Distill-Qwen-1.5B
trust_remote_code: true

### method
stage: kto
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all
pref_beta: 0.1  # KL divergence hyperparam

### dataset
dataset: 1.5B_math500_pass@5_solutions_kto
template: deepseek3
cutoff_len: 16384  # 16384  # 32768  # 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /n/netscratch/sham_lab/Everyone/jbejjani/saves/deepseek-r1-1.5b/1.5B_math500_pass@5_solutions_kto/lora/kto/3ep
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 3.0e-5  # 8.0e-5  # 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
