### model
model_name_or_path: /n/holylabs/LABS/sham_lab/Users/jbejjani/DeepSeek-V3/models/DeepSeek-R1-Distill-Qwen-1.5B
reward_model: saves/llama3-8b/lora/reward
trust_remote_code: true

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all

### dataset
dataset: 1.5B_pass@5_correct_math500_solutions
template: deepseek3
cutoff_len: 32768
max_samples: 3000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/deepseek-r1-1.5b/1.5B_pass@5_correct_math500_solutions/lora/ppo/3ep/new_hyperparams/cosine
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 3.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

### generate
max_new_tokens: 4096  # 512
top_k: 0
top_p: 0.9
