### model
model_name_or_path: /n/holylabs/LABS/sham_lab/Users/jbejjani/Llama3/models/Meta-Llama-3-8B-Instruct
trust_remote_code: true

### method
stage: kto
do_train: true
finetuning_type: lora
lora_rank: 16  # 8
lora_target: all
pref_beta: 0.1

### dataset
dataset: llama8B_math500_solutions_kto
template: llama3
cutoff_len: 4096  # 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /n/netscratch/sham_lab/Everyone/jbejjani/saves/llama3-8b/lora/kto/llama8B_math500_solutions_kto
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### wandb logging
report_to: wandb
run_name: llama3_8B_lora_kto_math500_solutions_3ep

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
