### model
model_name_or_path: /n/holylabs/LABS/sham_lab/Users/jbejjani/DeepSeek-V3/models/DeepSeek-R1-Distill-Qwen-1.5B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: 32B_correct_verifications_of_1.5B_math500_solutions
template: deepseek3
cutoff_len: 32768
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /n/netscratch/sham_lab/Everyone/jbejjani/output/deepseek_r1_1.5B_full_sft/maxcutoff_32768/32B_correct_verifications_of_1.5B_math500_solutions
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### wandb logging
report_to: wandb
run_name: 1.5B_full_sft_32B_correct_verifications_of_1.5B_math500_solutions

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
